mysql:
  host: 127.0.0.1
  port: "3306"
  user: root
  password: "123456"
  database: gin-quasar-admin
  maxIdle: 0
  maxOpen: 0
system:
  port: 8888
  successCode: 1
  successMessage: 操作成功！
  errorCode: 0
  errorMessage: 操作失败！
  bindError: 入参校验失败！
  genPluginPath: gqaplugin/template
zap:
  prefix: '[gin-quasar-admin]'
  level: info
  path: gqa-log
  filename: gqa-log
  maxSize: 200
  maxBackups: 10
  maxAge: 8
