casbin:
  model-path: ./config/rbac_model.conf
jwt:
  issuer: gin-quasar-admin
  secret-key: gin-quasar-admin
  expires-at: 604800
  buffer-time: 86400
mysql:
  path:
  config:
  db-name:
  username:
  password: 
  max-idle-conns: 0
  max-open-conns: 0
  log-mode: ""
  log-zap: false
system:
  port: 8888
  success-code: 1
  success-message: 操作成功
  error-code: 0
  error-message: 操作失败
upload:
  avatar-save-path: upload/avatar
  avatar-url: avatar
  file-save-path: upload/file
  file-url: file
zap:
  prefix: 【gin-quasar-admin】
  level: info
  filepath: log
  filename: gqa-log
  max-size: 200
  max-age: 8
  max-backups: 10
